/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/astronaut1.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.animated.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="animacao" position={[0, 1.3, 0.05]} rotation={[3.08, -1.5, -3.02]} scale={[0.03, 0.03, 0.03]}>
        <primitive object={nodes.Bip001_Pelvis} />
        <skinnedMesh
          geometry={nodes.tulovishe_lo_1.geometry}
          material={materials.astronaut}
          skeleton={nodes.tulovishe_lo_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.tulovishe_lo_2.geometry}
          material={materials.metl}
          skeleton={nodes.tulovishe_lo_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.tulovishe_lo_3.geometry}
          material={materials.steklo}
          skeleton={nodes.tulovishe_lo_3.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/astronaut1.glb')
