/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes } = useGLTF('/Mercury.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Asset3DLoadersceneRoot.geometry} material={nodes.Asset3DLoadersceneRoot.material} scale={14.16}/>
    </group>
  )
}

useGLTF.preload('/Mercury.glb')
