/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sun.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mars.geometry} material={materials['Mars.001']} position={[0, 4.42, 0]} scale={4.16} />
    </group>
  )
}

useGLTF.preload('/sun.glb')
