/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Uranus.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} scale={0.019}/>
      <mesh geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} scale={0.019}/>
    </group>
  )
}

useGLTF.preload('/Uranus.glb')
